#include <stm32f446re.h>

void SPI2_GPIO_INIT(void) {

	GPIO_Handle SPIPins;

	SPIPins.pGPIOX = GPIOB;
	SPIPins.GPIOX_PINCONFIG.GPIO_PinMode = GPIO_MODE_ALTFN;
	SPIPins.GPIOX_PINCONFIG.GPIO_PinOTYPE = GPIO_OTYPE_PUSHPULL;
	SPIPins.GPIOX_PINCONFIG.GPIO_PinPUPD = GPIO_PUPD_NO;
	SPIPins.GPIOX_PINCONFIG.GPIO_PinSpeed = GPIO_SPEED_FAST;
	SPIPins.GPIOX_PINCONFIG.GPIO_PinALTFMode = 5;

	SPIPins.GPIOX_PINCONFIG.GPIO_PinNumber = GPIO_PIN_13;
	GPIO_INIT(&SPIPins);

	SPIPins.GPIOX_PINCONFIG.GPIO_PinNumber = GPIO_PIN_15;
	GPIO_INIT(&SPIPins);

}

void SPI2_INIT(void) {

	SPI_HANDLE SPI2Handle;

	SPI2Handle.pSPIX = SPI2;
	SPI2Handle.SPIX_CONFIG.SPI_DeviceMode = SPI_DEVICEMODE_MASTER;
	SPI2Handle.SPIX_CONFIG.SPI_BusConfig = SPI_BUS_CONFIG_HD;
	SPI2Handle.SPIX_CONFIG.SPI_SCLKSpeed = SPI_SCLKSPEED_DIV8;
	SPI2Handle.SPIX_CONFIG.SPI_DFF = SPI_DFF_8BIT;
	SPI2Handle.SPIX_CONFIG.SPI_CPOL = SPI_CPOL_LOW;
	SPI2Handle.SPIX_CONFIG.SPI_CPHA = SPI_CPHA_LOW;
	SPI2Handle.SPIX_CONFIG.SPI_SSM = SPI_SSM_EN;

	SPI_INIT(&SPI2Handle);

}

int main(void) {

	uint8_t data = 0xA5;

	SPI2_GPIO_INIT();
	SPI2_INIT();

	SPI_SSI_CONTROL(SPI2, ENABLE);
	SPI_PERI_CONTROL(SPI2, ENABLE);

	while(1) {

		SPI_SEND(SPI2, &data, 1);

		while(SPI_GETFLAG(SPI2, SPI_BUSY_FLAG));

	}

}
